### ISSUE TITLE
Create button to import tokens into wallet from Neon-Faucet

### ISSUE THREAD

**Issue by ivandzen** [neonevm/neon-faucet-ui#16]
Currently, users have to manually import devnet/testnet ERC20 tokens to theirs metamask wallet. This approach is quite tricky: user have to find out required token address, copy it, setup metamask an so on.
It is suggested to implement additional UI element (button or token-list table) on neonfaucet which will automatically import selected token into metamask.

**Comment by ivandzen** [comment]
Maybe even import tokens when clicking 'test airdrop'?

**Comment by zapolnoch** [comment]
moved to NDEV-545
